#!/bin/bash
# This script uploads an program to Weptech Saker
# First reboot device and press BTN1 (second from the USB-connector) 
# to start the bootloader
# Inx-Service (c) Veikko Kero 2017

cd /home/$USER/upload-scripts

echo -e "\nGood Day to you Sir! Let's program Weptech Saker.\n"
echo "Please select the program you want to upload: "
echo "	[1] CC1200 Sub-1GHz"
echo "	[2] CC2538 2.54GHz"
echo "	[X] EXIT"

while true; do
    read -p "-> " ans
    case $ans in
        [1]* ) PROGRAM=./br-cc1200.bin; 
	       echo -e "You've selected 'br-cc1200.bin'. Let's start! \n"; 
		break;;
        [2]* ) PROGRAM=./br-cc2538.bin; 
		echo -e "You've selected 'br-cc2538.bin'. Let's start! \n"; 
		break;;
	[Xx]* ) echo "Take care now, bye bye then!"; exit;;
        * ) echo "Please check your options!";;
    esac
done

sudo python /home/user/contiki-weptech/tools/cc2538-bsl/cc2538-bsl.py -e -w -v $PROGRAM

echo ""
echo "Hope you had any luck today!"
read -p "Press any key to continue... "

