#!/bin/bash

cd ~/upload-scripts
echo -e "\nGood Day to you Sir! Let's program Weptech Saker."

## array of menu entries
entries=( "CC1200 Sub-1GHz"
	"CC2538 2.54GHz"
	"Thingsquare Firmware 868MHz"
	"EXIT" )

## set prompt for select menu
PS3='Selection: '

while [ "$menu" != 1 ]; do               		## outer loop redraws menu each time
 	## heading for menu
	printf "\nPlease select the program you want to upload:\n"          
	select choice in "${entries[@]}"; do  		## select displays choices in array
        	case "$choice" in                	## case responds to choice
            		"CC1200 Sub-1GHz" )
               			echo -e "You've selected 'br-cc1200.bin'. Let's start! \n"; 
				PROGRAM=./br-cc1200.bin; 
				menu=2
               			break                     
                		;;
            		"CC2538 2.54GHz" )         
		       		 echo -e "You've selected 'br-cc2538.bin'. Let's start! \n";   
				PROGRAM=./br-cc2538.bin; 
				menu=2                        
		        	break
		        	;;
            		"Thingsquare Firmware 868MHz" )
		        	echo -e "You've selected 'weptech-868mhz.bin'. Let's start! \n";
				PROGRAM=./weptech-868mhz.bin; 
				menu=2
				break
		        	;;
            		"EXIT" )
				echo "Take care now, bye bye then!";            
		        	menu=1                    
		        	break
		        	;;
           		 * )
		        	echo "Please check your options!"
		        	;;
		esac
	done

   	while [ "$menu" -eq 2 ]; do
		sudo python ~/contiki-weptech/tools/cc2538-bsl/cc2538-bsl.py -e -w -v $PROGRAM

		echo -e "\nHope you had any luck today!"
		read -p "Do you want to try again? (y/n) " yn
		case $yn in
			[Yy]* ) echo "Ok!";  
				break
				;;
			[Nn]* ) echo "Take care now, bye bye then!";
				menu=1                    
		        	break
		        	;;
			* ) 	
				echo "Please answer 'y' or 'n'"
				;;
	esac
    done
	
done

exit 0
